# Offense count: 4
Metrics/AbcSize:
  Max: 50

# Offense count: 2
Metrics/CyclomaticComplexity:
  Max: 10

# Offense count: 49
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 121

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 41

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 250

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "spec/**/*"

Layout/CaseIndentation:
  EnforcedStyle: end

# do not work properly
Style/NegatedIf:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  EnforcedStyle: only_raise

# Offense count: 340
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
Style/WordArray:
  Enabled: false

# we intentionally ignore some exceptions in fork as we have no way to report it back
Lint/HandleExceptions:
  Enabled: false
